namespace Murchalka.ModuleProtocol.Contracts;

/// <summary>Requests rotation of an enrolled Node certificate while retaining its private key.</summary>
/// <param name="NodeId">The enrolled Node identifier.</param>
/// <param name="PublicKeySpki">The Base64 DER SubjectPublicKeyInfo generated by the Node.</param>
public sealed record NodeCertificateRenewalRequest(NodeId NodeId, string PublicKeySpki);
